// routes/reportRoutes.js
import express from "express";
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import db from "../db.js";
import cors from "cors";

const router = express.Router();

// Utility: mock AI summary generator
function generateFakeAIInsight(event, totalRegs, totalCash) {
  return `
The event "${event.title}" in the category "${event.category}" was successfully organized 
on ${event.date}. It achieved good student participation with ${totalRegs} total registrations.

💡 AI Summary:
- The engagement level was impressive given the event’s academic focus.
- The total amount collected (₹${totalCash}) indicates strong community support.
- For future improvement, consider expanding promotion to other departments 
  and offering early-bird registration incentives.

Overall, this event showcased effective planning and execution within the institution.
  `;
}

router.post("/generate", async (req, res) => {
  const { eventId } = req.body;

  try {
    // 1️⃣ Fetch event details
    const [eventData] = await db.execute("SELECT * FROM events WHERE id = ?", [eventId]);
    if (eventData.length === 0) return res.status(404).json({ message: "Event not found" });
    const event = eventData[0];

    // 2️⃣ Fetch registrations
    const [registrations] = await db.execute(
      "SELECT * FROM registrations WHERE eventId = ?",
      [eventId]
    );

    // 3️⃣ Fetch finance data
    const [financeData] = await db.execute("SELECT * FROM finance WHERE eventId = ?", [eventId]);
    const finance = financeData[0] || { cashCollected: 0, onlineCollected: 0 };
    const totalCollected = Number(finance.cashCollected) + Number(finance.onlineCollected);

    // 4️⃣ Generate AI-like insight (mock)
    const aiInsight = generateFakeAIInsight(event, registrations.length, totalCollected);

    // 5️⃣ Generate PDF
    const doc = new PDFDocument({ margin: 50 });
    const pdfPath = path.join("public", `EventReport_${event.title}.pdf`);
    const writeStream = fs.createWriteStream(pdfPath);
    doc.pipe(writeStream);

    // Header
    doc.fontSize(22).text("🎓 AI Campus Event Report", { align: "center" });
    doc.moveDown();

    // Event Info
    doc.fontSize(14).text(`Event: ${event.title}`);
    doc.text(`Category: ${event.category}`);
    doc.text(`Date: ${event.date}`);
    doc.text(`Venue: ${event.venue || "N/A"}`);
    doc.text(`Location: ${event.location || "N/A"}`);
    doc.moveDown();

    // Financial
    doc.fontSize(14).text("💰 Financial Summary");
    doc.text(`Cash Collected: ₹${finance.cashCollected}`);
    doc.text(`Online Collected: ₹${finance.onlineCollected}`);
    doc.text(`Total Collected: ₹${totalCollected}`);
    doc.moveDown();

    // Registration
    doc.fontSize(14).text("👥 Registrations");
    doc.text(`Total Registered Students: ${registrations.length}`);
    doc.moveDown();

    // AI Summary
    doc.fontSize(14).text("💡 AI Insight", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text(aiInsight, { align: "justify" });
    doc.moveDown(1);

    // Footer
    doc.fontSize(10).text("Generated by AI Campus Event Monitoring System", {
      align: "center",
      opacity: 0.6,
    });

    doc.end();

    writeStream.on("finish", () => {
      res.download(pdfPath);
    });
  } catch (error) {
    console.error("❌ Error generating report:", error);
    res.status(500).json({ message: "Error generating report" });
  }
});

export default router; 